### ISSUE TITLE
Solve the loading of libblas for all Linux distributions.

### ISSUE THREAD

**Issue by ladc** [ladc/lgsl#11]
I wrote:

> I thought I had solved the issue [#4], but apparently CentOS has a different libblas.so, which doesn't contain the necessary symbols. Instead they are in libgslcblas.so. Sigh.

**Comment by franko** [comment]
You know my point of view: make a good, reasonable makefile that works on most systems. Inevitably on some systems something will not work. Just put there some INSTALL information and people will be able to fix things. Otherwise it is the job of the package maintainer for each distribution to fix the details.

People made the package configurations for GSL Shell on Arch linux and gentoo but unfortunately not on debian!

If there is a problem of this kind in CentOS just put the information in the INSTALL or README file so that people can be aware of this problem and maybe find a fix.

**Comment by ladc** [comment]
Since LGSL ideally only depends on GSL, I removed the libblas dependency. Loading libgslcblas should work fine everywhere (though suboptimally).
Fixed in c74b91c.
